
/**
* This playwright test file has been auto-generated from
* the VR test file at: /Users/skanodia/dev/jira-frontend/dev-tooling/packages/experimental-vr-testing/vr-tests/border-radius.vr.ts
*
* Do not edit this file directly.
*/
// @ts-nocheck
/* eslint-disable */

import {
    SecondaryPaletteBorderRadius,
    ExtendedPaletteBorderRadius,
} from './examples';
import { expect, test } from "../fixtures/baseFixtures.ts";

    test('secondary palette border radius', async ({ mount }) => {
        test.info().annotations.push({ type: 'componentName', description: 'SecondaryPaletteBorderRadius' });

        const component = await mount(
            <SecondaryPaletteBorderRadius />,
        );
        await expect(component).toHaveScreenshot()
    });

    test('extended palette border radius', async ({ mount }) => {


        test.info().annotations.push({ type: 'componentName', description: 'ExtendedPaletteBorderRadius' });

        const component = await mount(
            <ExtendedPaletteBorderRadius />
        );

        await expect(component).toHaveScreenshot()
});

